const templates = [
  // =========================================
  // 1. INSTAGRAM SALES DM
  // =========================================
  { id: 1, category: "Instagram Sales", title: "Warm Lead DM", content: "Hey 👋 I noticed you were interested in our product. Do you have any questions I can help with?" },
  { id: 2, category: "Instagram Sales", title: "Limited Offer DM", content: "We’re closing this offer tonight. I wanted to make sure you don’t miss it." },
  { id: 3, category: "Instagram Sales", title: "Reactivation Message", content: "Hi again! Just checking in to see if you’re still considering moving forward." },
  { id: 4, category: "Instagram Sales", title: "Warm Lead DM 1", content: "Hey 👋 I noticed you were interested in our product. Do you have any questions I can help with?" },
  { id: 5, category: "Instagram Sales", title: "Warm Lead DM 2", content: "Hi! Just wanted to check if you’re ready to get started with our service." },
  { id: 6, category: "Instagram Sales", title: "Warm Lead DM 3", content: "Hello 👋 We have an offer running this week. Would you like to know more?" },
  { id: 7, category: "Instagram Sales", title: "Warm Lead DM 4", content: "Hi! I can help you choose the right plan for your needs." },
  { id: 8, category: "Instagram Sales", title: "Warm Lead DM 5", content: "Hey there! Have you seen our latest product update?" },
  { id: 9, category: "Instagram Sales", title: "Warm Lead DM 6", content: "Hi! Just following up to see if you had a chance to review our proposal." },
  { id: 10, category: "Instagram Sales", title: "Warm Lead DM 7", content: "Hello! Quick question — what’s your biggest challenge right now?" },
  { id: 11, category: "Instagram Sales", title: "Warm Lead DM 8", content: "Hey! We just launched a new feature that might interest you." },
  { id: 12, category: "Instagram Sales", title: "Warm Lead DM 9", content: "Hi! Do you prefer a quick demo or a detailed walkthrough?" },
  { id: 13, category: "Instagram Sales", title: "Warm Lead DM 10", content: "Hello 👋 I can guide you step by step to get started today." },
  { id: 14, category: "Instagram Sales", title: "Warm Lead DM 11", content: "Hey! Limited spots are available for onboarding this week." },
  { id: 15, category: "Instagram Sales", title: "Warm Lead DM 12", content: "Hi! Many of our clients saw results within the first week." },
  { id: 16, category: "Instagram Sales", title: "Warm Lead DM 13", content: "Hello! Want me to share a quick tip to improve your workflow?" },
  { id: 17, category: "Instagram Sales", title: "Warm Lead DM 14", content: "Hey! We’ve helped businesses like yours increase conversions fast." },
  { id: 18, category: "Instagram Sales", title: "Warm Lead DM 15", content: "Hi! Are you looking for a simple or advanced solution?" },
  { id: 19, category: "Instagram Sales", title: "Warm Lead DM 16", content: "Hello! I can provide a tailored recommendation for your business." },
  { id: 20, category: "Instagram Sales", title: "Warm Lead DM 17", content: "Hey! Just checking if you received my last message." },
  { id: 21, category: "Instagram Sales", title: "Warm Lead DM 18", content: "Hi! Can I show you a quick demo of what we offer?" },
  { id: 22, category: "Instagram Sales", title: "Warm Lead DM 19", content: "Hello! This solution is perfect for your current challenge." },
  { id: 23, category: "Instagram Sales", title: "Warm Lead DM 20", content: "Hey! I can share a success story similar to your business." },
  { id: 24, category: "Instagram Sales", title: "Warm Lead DM 21", content: "Hi! Would you like a free consultation call?" },
  { id: 25, category: "Instagram Sales", title: "Warm Lead DM 22", content: "Hello! I can answer any questions about our product today." },
  { id: 26, category: "Instagram Sales", title: "Warm Lead DM 23", content: "Hey! Don’t miss out on our limited-time offer." },
  { id: 27, category: "Instagram Sales", title: "Warm Lead DM 24", content: "Hi! Have you considered how this could save you time?" },
  { id: 28, category: "Instagram Sales", title: "Warm Lead DM 25", content: "Hello! I can help you get results faster than competitors." },
  { id: 29, category: "Instagram Sales", title: "Warm Lead DM 26", content: "Hey! What’s your preferred way to get started — chat or call?" },
  { id: 30, category: "Instagram Sales", title: "Warm Lead DM 27", content: "Hi! Just a reminder, our spots for onboarding are limited." },
  { id: 31, category: "Instagram Sales", title: "Warm Lead DM 28", content: "Hello! Many clients achieved great ROI with our service." },
  { id: 32, category: "Instagram Sales", title: "Warm Lead DM 29", content: "Hey! I can send you a quick guide to understand our solution." },
  { id: 33, category: "Instagram Sales", title: "Warm Lead DM 30", content: "Hi! We have a special plan tailored for businesses like yours." },
  { id: 34, category: "Instagram Sales", title: "Warm Lead DM 31", content: "Hello! Want me to walk you through the setup process?" },
  { id: 35, category: "Instagram Sales", title: "Warm Lead DM 32", content: "Hey! Do you prefer a written guide or a video demo?" },
  { id: 36, category: "Instagram Sales", title: "Warm Lead DM 33", content: "Hi! Let’s schedule a short call to discuss your needs." },
  { id: 37, category: "Instagram Sales", title: "Warm Lead DM 34", content: "Hello! I can share tips that helped other clients double their results." },
  { id: 38, category: "Instagram Sales", title: "Warm Lead DM 35", content: "Hey! Our solution adapts to your exact workflow." },
  { id: 39, category: "Instagram Sales", title: "Warm Lead DM 36", content: "Hi! I can provide insights to optimize your process quickly." },
  { id: 40, category: "Instagram Sales", title: "Warm Lead DM 37", content: "Hello! Want a step-by-step plan to get started today?" },
  { id: 41, category: "Instagram Sales", title: "Warm Lead DM 38", content: "Hey! Quick question — what’s your main goal this month?" },
  { id: 42, category: "Instagram Sales", title: "Warm Lead DM 39", content: "Hi! I can help you overcome common obstacles easily." },
  { id: 43, category: "Instagram Sales", title: "Warm Lead DM 40", content: "Hello! Want a quick walkthrough to see if this fits your needs?" },
  { id: 44, category: "Instagram Sales", title: "Warm Lead DM 41", content: "Hey! We’ve recently improved features that might help you." },
  { id: 45, category: "Instagram Sales", title: "Warm Lead DM 42", content: "Hi! Just following up in case you missed my last message." },
  { id: 46, category: "Instagram Sales", title: "Warm Lead DM 43", content: "Hello! Want a free tip that could improve your conversions?" },
  { id: 47, category: "Instagram Sales", title: "Warm Lead DM 44", content: "Hey! Many clients doubled results within the first week." },
  { id: 48, category: "Instagram Sales", title: "Warm Lead DM 45", content: "Hi! I can send you an overview to help you decide faster." },
  { id: 49, category: "Instagram Sales", title: "Warm Lead DM 46", content: "Hello! Want a quick example of how it works?" },
  { id: 50, category: "Instagram Sales", title: "Warm Lead DM 47", content: "Hey! Do you prefer text instructions or video guidance?" },
  { id: 51, category: "Instagram Sales", title: "Warm Lead DM 48", content: "Hi! I can share a roadmap to get you started immediately." },
  { id: 52, category: "Instagram Sales", title: "Warm Lead DM 49", content: "Hello! Many of our clients saw success in under a week." },
  { id: 53, category: "Instagram Sales", title: "Warm Lead DM 50", content: "Hey! Want a free consultation to see how this fits your business?" },

  // =========================================
  // 2. HIGH TICKET SALES
  // =========================================
  { id: 54, category: "High Ticket Sales", title: "Authority Close", content: "Based on your goals, this premium solution is exactly what you need." },
  { id: 55, category: "High Ticket Sales", title: "Scarcity Close", content: "We only accept 5 new clients per month to maintain quality." },
  { id: 56, category: "High Ticket Sales", title: "Confidence Close", content: "If you’re serious about results, this is the right move." },
  { id: 57, category: "High Ticket Sales", title: "Authority Close 1", content: "Based on your goals, this premium solution is exactly what you need." },
  { id: 58, category: "High Ticket Sales", title: "Authority Close 2", content: "This program is tailored to help you achieve maximum results efficiently." },
  { id: 59, category: "High Ticket Sales", title: "Authority Close 3", content: "We’ve helped top clients like you exceed their targets quickly." },
  { id: 60, category: "High Ticket Sales", title: "Scarcity Close 1", content: "We only accept 5 new clients per month to maintain quality." },
  { id: 61, category: "High Ticket Sales", title: "Scarcity Close 2", content: "Enrollment is limited to ensure personalized attention." },
  { id: 62, category: "High Ticket Sales", title: "Scarcity Close 3", content: "Seats are filling fast. Secure your spot before it’s gone." },
  { id: 63, category: "High Ticket Sales", title: "Confidence Close 1", content: "If you’re serious about results, this is the right move." },
  { id: 64, category: "High Ticket Sales", title: "Confidence Close 2", content: "We guarantee measurable growth or your investment back." },
  { id: 65, category: "High Ticket Sales", title: "Confidence Close 3", content: "This solution has consistently outperformed alternatives in the market." },
  { id: 66, category: "High Ticket Sales", title: "High Ticket Offer 1", content: "Only clients ready to take massive action should join this program." },
  { id: 67, category: "High Ticket Sales", title: "High Ticket Offer 2", content: "We focus on results, not just promises — are you ready to commit?" },
  { id: 68, category: "High Ticket Sales", title: "High Ticket Offer 3", content: "Our approach is designed for serious clients who want extraordinary outcomes." },
  { id: 69, category: "High Ticket Sales", title: "Premium Solution 1", content: "This strategy is personalized for your business to maximize ROI." },
  { id: 70, category: "High Ticket Sales", title: "Premium Solution 2", content: "We implement advanced methods used by top performers in your industry." },
  { id: 71, category: "High Ticket Sales", title: "Premium Solution 3", content: "Clients who followed this approach doubled their revenue in months." },
  { id: 72, category: "High Ticket Sales", title: "Authority Close 4", content: "Our proven system removes guesswork and ensures consistent results." },
  { id: 73, category: "High Ticket Sales", title: "Scarcity Close 4", content: "Limited availability ensures you get the attention your business deserves." },
  { id: 74, category: "High Ticket Sales", title: "Confidence Close 4", content: "We stand behind our methods — your success is our priority." },
  { id: 75, category: "High Ticket Sales", title: "High Ticket Offer 4", content: "This is designed for clients ready to invest in significant growth." },
  { id: 76, category: "High Ticket Sales", title: "Premium Solution 4", content: "Our solution adapts to your unique challenges and opportunities." },
  { id: 77, category: "High Ticket Sales", title: "Authority Close 5", content: "Join a program that aligns with your ambitions and targets." },
  { id: 78, category: "High Ticket Sales", title: "Scarcity Close 5", content: "Few spots remain. Don’t wait until the next opening." },
  { id: 79, category: "High Ticket Sales", title: "Confidence Close 5", content: "Serious clients see the results they expect — and more." },
  { id: 80, category: "High Ticket Sales", title: "High Ticket Offer 5", content: "We only work with those committed to growth and action." },
  { id: 81, category: "High Ticket Sales", title: "Premium Solution 5", content: "Each client receives a tailored roadmap to reach their goals." },
  { id: 82, category: "High Ticket Sales", title: "Authority Close 6", content: "Our expert guidance eliminates trial-and-error in your strategy." },
  { id: 83, category: "High Ticket Sales", title: "Scarcity Close 6", content: "Availability is extremely limited. Act now to secure your spot." },
  { id: 84, category: "High Ticket Sales", title: "Confidence Close 6", content: "We provide results-focused solutions for ambitious clients." },
  { id: 85, category: "High Ticket Sales", title: "High Ticket Offer 6", content: "Designed for action-takers ready to achieve real impact." },
  { id: 86, category: "High Ticket Sales", title: "Premium Solution 6", content: "Our approach is structured for measurable, predictable outcomes." },
  { id: 87, category: "High Ticket Sales", title: "Authority Close 7", content: "This premium program is recognized for delivering industry-leading results." },
  { id: 88, category: "High Ticket Sales", title: "Scarcity Close 7", content: "Act quickly — only a few openings remain this month." },
  { id: 89, category: "High Ticket Sales", title: "Confidence Close 7", content: "We guarantee expert guidance and proven results for serious clients." },
  { id: 90, category: "High Ticket Sales", title: "High Ticket Offer 7", content: "Perfect for clients committed to achieving accelerated growth." },
  { id: 91, category: "High Ticket Sales", title: "Premium Solution 7", content: "Our strategies are crafted to fit your exact business needs." },
  { id: 92, category: "High Ticket Sales", title: "Authority Close 8", content: "Clients trust our approach because it delivers consistent success." },
  { id: 93, category: "High Ticket Sales", title: "Scarcity Close 8", content: "Limited slots ensure you get top-tier support and results." },
  { id: 94, category: "High Ticket Sales", title: "Confidence Close 8", content: "Our team is dedicated to helping you achieve measurable outcomes." },
  { id: 95, category: "High Ticket Sales", title: "High Ticket Offer 8", content: "This program is exclusively for clients ready to take massive action." },
  { id: 96, category: "High Ticket Sales", title: "Premium Solution 8", content: "We provide a step-by-step roadmap to maximize your growth potential." },
  { id: 97, category: "High Ticket Sales", title: "Authority Close 9", content: "Join a program built to accelerate ambitious businesses like yours." },
  { id: 98, category: "High Ticket Sales", title: "Scarcity Close 9", content: "Few spots left — secure your place to get full benefits." },
  { id: 99, category: "High Ticket Sales", title: "Confidence Close 9", content: "Our solutions are proven to deliver measurable results every time." },
  { id: 100, category: "High Ticket Sales", title: "High Ticket Offer 9", content: "Perfect for clients serious about taking their business to the next level." },
  { id: 101, category: "High Ticket Sales", title: "Premium Solution 9", content: "We design strategies that are tailored to your unique goals." },
  { id: 102, category: "High Ticket Sales", title: "Authority Close 10", content: "This program ensures maximum ROI through proven methods." },
  { id: 103, category: "High Ticket Sales", title: "Scarcity Close 10", content: "Availability is extremely limited — act now to secure your spot." },
  { id: 104, category: "High Ticket Sales", title: "Confidence Close 10", content: "We provide results-focused guidance to clients ready for action." },
  { id: 105, category: "High Ticket Sales", title: "High Ticket Offer 10", content: "Our offer is designed for serious clients seeking real business impact." },
  { id: 106, category: "High Ticket Sales", title: "Premium Solution 10", content: "Each client receives personalized strategies to achieve their goals." },

  // =========================================
  // 3. FREELANCER SCRIPTS
  // =========================================
  { id: 107, category: "Freelancer Scripts", title: "Project Proposal", content: "Thank you for the opportunity. Here’s how I plan to execute your project successfully." },
  { id: 108, category: "Freelancer Scripts", title: "Price Justification", content: "My rate reflects the quality, experience, and guaranteed delivery." },
  { id: 109, category: "Freelancer Scripts", title: "Client Follow Up", content: "Just checking in regarding the project timeline." },
  { id: 110, category: "Freelancer Scripts", title: "Project Proposal 1", content: "Thank you for the opportunity. Here’s how I plan to execute your project successfully." },
  { id: 111, category: "Freelancer Scripts", title: "Project Proposal 2", content: "I’ve outlined a step-by-step plan to ensure timely and high-quality delivery." },
  { id: 112, category: "Freelancer Scripts", title: "Project Proposal 3", content: "This approach maximizes efficiency while keeping your objectives in focus." },
  { id: 113, category: "Freelancer Scripts", title: "Price Justification 1", content: "My rate reflects the quality, experience, and guaranteed delivery." },
  { id: 114, category: "Freelancer Scripts", title: "Price Justification 2", content: "Investing in quality now saves time and cost later." },
  { id: 115, category: "Freelancer Scripts", title: "Price Justification 3", content: "This pricing ensures premium results aligned with your goals." },
  { id: 116, category: "Freelancer Scripts", title: "Client Follow Up 1", content: "Just checking in regarding the project timeline." },
  { id: 117, category: "Freelancer Scripts", title: "Client Follow Up 2", content: "I wanted to ensure everything is progressing smoothly." },
  { id: 118, category: "Freelancer Scripts", title: "Client Follow Up 3", content: "Let me know if you need any adjustments or further clarification." },
  { id: 119, category: "Freelancer Scripts", title: "Proposal Enhancement 1", content: "I’ve added extra insights to optimize your project outcomes." },
  { id: 120, category: "Freelancer Scripts", title: "Proposal Enhancement 2", content: "Here’s an updated strategy to improve efficiency and impact." },
  { id: 121, category: "Freelancer Scripts", title: "Proposal Enhancement 3", content: "This addition ensures your project meets high standards." },
  { id: 122, category: "Freelancer Scripts", title: "Client Motivation 1", content: "Taking action now can lead to faster results and higher ROI." },
  { id: 123, category: "Freelancer Scripts", title: "Client Motivation 2", content: "Implementing this plan today will set your project ahead." },
  { id: 124, category: "Freelancer Scripts", title: "Client Motivation 3", content: "Starting immediately ensures optimal efficiency and success." },
  { id: 125, category: "Freelancer Scripts", title: "Project Update 1", content: "I’ve completed the initial stage; here’s a brief report." },
  { id: 126, category: "Freelancer Scripts", title: "Project Update 2", content: "The progress is on track and aligned with the set milestones." },
  { id: 127, category: "Freelancer Scripts", title: "Project Update 3", content: "All deliverables are being handled as per the timeline." },
  { id: 128, category: "Freelancer Scripts", title: "Feedback Request 1", content: "Could you share your thoughts on the latest draft?" },
  { id: 129, category: "Freelancer Scripts", title: "Feedback Request 2", content: "Your feedback will help refine the output to your preference." },
  { id: 130, category: "Freelancer Scripts", title: "Feedback Request 3", content: "Let me know if any adjustments are required." },
  { id: 131, category: "Freelancer Scripts", title: "Follow Up 4", content: "Just a quick reminder about the pending review." },
  { id: 132, category: "Freelancer Scripts", title: "Follow Up 5", content: "Please confirm if the last submission meets your expectations." },
  { id: 133, category: "Freelancer Scripts", title: "Follow Up 6", content: "Awaiting your feedback to move to the next stage." },
  { id: 134, category: "Freelancer Scripts", title: "Value Reminder 1", content: "This approach ensures long-term efficiency and quality." },
  { id: 135, category: "Freelancer Scripts", title: "Value Reminder 2", content: "Investing now guarantees superior outcomes later." },
  { id: 136, category: "Freelancer Scripts", title: "Value Reminder 3", content: "Our plan is designed to maximize return on your investment." },
  { id: 137, category: "Freelancer Scripts", title: "Proposal Check 1", content: "I’ve reviewed all aspects to ensure your objectives are met." },
  { id: 138, category: "Freelancer Scripts", title: "Proposal Check 2", content: "Every step is aligned with your project goals." },
  { id: 139, category: "Freelancer Scripts", title: "Proposal Check 3", content: "This plan provides clarity, structure, and measurable outcomes." },
  { id: 140, category: "Freelancer Scripts", title: "Client Assurance 1", content: "You can rely on consistent updates and transparency." },
  { id: 141, category: "Freelancer Scripts", title: "Client Assurance 2", content: "Your project will be handled with utmost professionalism." },
  { id: 142, category: "Freelancer Scripts", title: "Client Assurance 3", content: "We prioritize timely delivery and high-quality results." },

  // =========================================
  // 4. E-COMMERCE REPLIES
  // =========================================
  { id: 143, category: "Ecommerce Replies", title: "Order Confirmation", content: "Your order has been successfully received and is being processed." },
  { id: 144, category: "Ecommerce Replies", title: "Shipping Update", content: "Your package is on the way! Tracking details have been sent." },
  { id: 145, category: "Ecommerce Replies", title: "Out of Stock Reply", content: "Unfortunately, this item is currently out of stock. Would you like to be notified when available?" },
  { id: 146, category: "Ecommerce Replies", title: "Order Confirmation 1", content: "Your order has been successfully received and is being processed." },
  { id: 147, category: "Ecommerce Replies", title: "Order Confirmation 2", content: "Thank you for your purchase! We’re preparing your order for shipment." },
  { id: 148, category: "Ecommerce Replies", title: "Order Confirmation 3", content: "We’ve received your order and will notify you once it’s shipped." },
  { id: 149, category: "Ecommerce Replies", title: "Shipping Update 1", content: "Your package is on the way! Tracking details have been sent." },
  { id: 150, category: "Ecommerce Replies", title: "Shipping Update 2", content: "Good news! Your order has been shipped and is expected to arrive soon." },
  { id: 151, category: "Ecommerce Replies", title: "Shipping Update 3", content: "We’ve updated your shipment status. You can track it here." },
  { id: 152, category: "Ecommerce Replies", title: "Out of Stock Reply 1", content: "Unfortunately, this item is currently out of stock. Would you like to be notified when available?" },
  { id: 153, category: "Ecommerce Replies", title: "Out of Stock Reply 2", content: "This product is temporarily unavailable. Can we alert you when it’s back in stock?" },
  { id: 154, category: "Ecommerce Replies", title: "Out of Stock Reply 3", content: "We’re restocking soon! Would you like to reserve one now?" },
  { id: 155, category: "Ecommerce Replies", title: "Delivery Delay 1", content: "We apologize for the delay. Your order is on its way and should arrive shortly." },
  { id: 156, category: "Ecommerce Replies", title: "Delivery Delay 2", content: "Shipping has been delayed slightly. We appreciate your patience." },
  { id: 157, category: "Ecommerce Replies", title: "Delivery Delay 3", content: "Your package will arrive soon. Thank you for bearing with us." },
  { id: 158, category: "Ecommerce Replies", title: "Order Issue 1", content: "We noticed an issue with your order. Can we help you correct it quickly?" },
  { id: 159, category: "Ecommerce Replies", title: "Order Issue 2", content: "There was a problem processing your order. Please contact us to resolve it." },
  { id: 160, category: "Ecommerce Replies", title: "Order Issue 3", content: "We’re here to help if your order didn’t go through correctly." },
  { id: 161, category: "Ecommerce Replies", title: "Refund Request 1", content: "Your refund request has been received and is being processed." },
  { id: 162, category: "Ecommerce Replies", title: "Refund Request 2", content: "We’ve approved your refund. The amount will reflect shortly." },
  { id: 163, category: "Ecommerce Replies", title: "Refund Request 3", content: "Your refund is on its way. Thank you for your patience." },
  { id: 164, category: "Ecommerce Replies", title: "Product Inquiry 1", content: "Hi! Can I provide more details about this product for you?" },
  { id: 165, category: "Ecommerce Replies", title: "Product Inquiry 2", content: "Let me know if you’d like additional specifications or photos." },
  { id: 166, category: "Ecommerce Replies", title: "Product Inquiry 3", content: "I’m happy to answer any questions about this item." },

  // =========================================
  // 5. OBJECTION HANDLING (جديد)
  // =========================================
  { id: 167, category: "Objection Handling", title: "Price Objection", content: "I understand the price is an investment. However, if you look at the ROI, it pays for itself in [X] months." },
  { id: 168, category: "Objection Handling", title: "Need to Think", content: "Take your time! Just so I know, is it the price, the timing, or something else holding you back?" },
  { id: 169, category: "Objection Handling", title: "Competitor Comparison", content: "Great question! What sets us apart is [Feature/Service] which most others don't offer." },

  // =========================================
  // 6. COACHING & CONSULTATION (جديد)
  // =========================================
  { id: 170, category: "Consultation", title: "Discovery Call Invite", content: "I’d love to learn more about your goals. Are you free for a quick 15-minute discovery call?" },
  { id: 171, category: "Consultation", title: "Post-Call Summary", content: "It was great speaking today! Here’s a summary of what we discussed and the next steps." },
  { id: 172, category: "Consultation", title: "Testimonial Request", content: "It’s been a pleasure working with you! Would you mind sharing a quick testimonial about your results?" },

  // =========================================
  // 7. REAL ESTATE (جديد)
  // =========================================
  { id: 173, category: "Real Estate", title: "Viewing Invitation", content: "We have an open house for this property this weekend. Would you like to reserve a time slot?" },
  { id: 174, category: "Real Estate", title: "Market Update", content: "Hi! Just wanted to share that property values in [Area] have increased this year. Great time to buy!" },
  { id: 175, category: "Real Estate", title: "Post-Viewing Follow-up", content: "Hi! How did you feel about the property we saw today? Does it match what you’re looking for?" },

  // =========================================
  // 8. CUSTOMER RETENTION (جديد)
  // =========================================
  { id: 176, category: "Retention", title: "Anniversary Discount", content: "Happy 1-year anniversary with us! Here’s a 20% discount code as a thank you for your loyalty." },
  { id: 177, category: "Retention", title: "Win-back Offer", content: "We haven’t seen you in a while! We’ve made some updates we think you’ll love. Want a demo?" },
  { id: 178, category: "Retention", title: "Referral Program", content: "Love our service? Refer a friend and you both get [Reward] on your next month!" }
];
